name: mint_admobkit
description: The flutter package including a set of AdMob integration utils for MintMinter apps
homepage: https://github.com/m11v/mint_admobkit
repository: https://github.com/m11v/mint_admobkit

version: 1.3.4

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  google_mobile_ads: ^5.1.0
  app_tracking_transparency: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
