name: mint_admobkit
description: A set of AdMob integration utils for MintMinter apps
version: 0.0.1
homepage: https://github.com/m11v/mint_admobkit
repository: https://github.com/m11v/mint_admobkit

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
